# claude-tui — install / uninstall
#
# `make install` copies the source to PREFIX/share/claude-tui, runs
# `bun install` there, and writes a launcher to PREFIX/bin/claude-tui.
# `make uninstall` removes both.
#
# Override PREFIX to install elsewhere:
#     make install PREFIX=/usr/local
#
# Defaults to ~/.local so a regular user install needs no sudo.

PREFIX     ?= $(HOME)/.local
BIN_DIR    := $(PREFIX)/bin
SHARE_DIR  := $(PREFIX)/share/claude-tui
LAUNCHER   := $(BIN_DIR)/claude-tui
PRELOAD    := $(SHARE_DIR)/node_modules/@opentui/solid/scripts/preload.ts
ENTRY      := $(SHARE_DIR)/src/index.tsx

# Files that need to live in the install dir for the app to run.
# node_modules is generated by `bun install` after the copy.
INSTALL_FILES := src package.json bun.lock bunfig.toml tsconfig.json README.md CLAUDE.md LICENSE

.PHONY: all help install uninstall reinstall check

all: help

help:
	@printf 'claude-tui — Makefile targets\n'
	@printf '\n'
	@printf '  make install     install to %s\n' '$(LAUNCHER)'
	@printf '  make uninstall   remove %s and %s\n' '$(LAUNCHER)' '$(SHARE_DIR)'
	@printf '  make reinstall   uninstall + install\n'
	@printf '  make check       typecheck the source\n'
	@printf '\n'
	@printf 'Override the install root with PREFIX (default: $$HOME/.local):\n'
	@printf '  make install PREFIX=/usr/local\n'

check:
	@bun run typecheck

# install is .PHONY so it ALWAYS runs. We don't gate on launcher mtime
# because the launcher is a 30-line shell script that doesn't change
# when source under src/<subdir>/ changes — make's directory mtime check
# wouldn't notice deep edits and you'd silently get a stale install.
install:
	@command -v bun >/dev/null 2>&1 || { \
	  printf 'error: bun is not installed (see https://bun.sh)\n' >&2 ; exit 1 ; }
	@printf '==> Staging source to %s\n' '$(SHARE_DIR)'
	@mkdir -p '$(SHARE_DIR)'
	@mkdir -p '$(BIN_DIR)'
	@# Wipe the staged src/ before recopying so deletions in the project
	@# (renamed or removed source files) propagate to the install dir.
	@# We don't wipe node_modules — that would force a slow reinstall
	@# every time. The dep tree only changes with package.json edits.
	@rm -rf '$(SHARE_DIR)/src'
	@cp -R $(INSTALL_FILES) '$(SHARE_DIR)/'
	@printf '==> Installing dependencies\n'
	@cd '$(SHARE_DIR)' && bun install --frozen-lockfile >/dev/null 2>&1 || \
	  cd '$(SHARE_DIR)' && bun install
	@printf '==> Writing launcher to %s\n' '$(LAUNCHER)'
	@printf '%s\n' \
	  '#!/bin/sh' \
	  '# claude-tui launcher — generated by `make install`. Re-run to regenerate.' \
	  '#' \
	  '# Why these flags:' \
	  '#   --conditions=browser  forces Bun to load Solid'"'"'s reactive build instead' \
	  '#                         of its SSR build (which would dispose unrelated' \
	  '#                         component scopes and break the dialog system).' \
	  '#   --preload <path>      pre-registers @opentui/solid'"'"'s JSX runtime so' \
	  '#                         <box>, <text>, <scrollbox>, etc. are available' \
	  '#                         when src/index.tsx is parsed.' \
	  '#' \
	  '# Note: we use `bun <file>` (NOT `bun run <file>`) so that any extra' \
	  '# arguments after the file are forwarded to the script as process.argv.' \
	  '# `bun run` would interpret them as flags to itself and reject anything' \
	  '# it does not recognise (e.g. --cwd, --debug).' \
	  '#' \
	  '# We do NOT cd into the install dir, so process.cwd() reflects wherever' \
	  '# the user invoked claude-tui from — that becomes the agent'"'"'s working' \
	  '# directory. We pass --cwd "$$PWD" first so it survives any --cwd the' \
	  '# user adds (parser walks left-to-right; last value wins).' \
	  '' \
	  'INSTALL_DIR="$(SHARE_DIR)"' \
	  'PRELOAD="$$INSTALL_DIR/node_modules/@opentui/solid/scripts/preload.ts"' \
	  'ENTRY="$$INSTALL_DIR/src/index.tsx"' \
	  '' \
	  'exec bun --conditions=browser --preload "$$PRELOAD" "$$ENTRY" --cwd "$$PWD" "$$@"' \
	  > '$(LAUNCHER)'
	@chmod +x '$(LAUNCHER)'
	@printf '\n'
	@printf 'Installed:  %s\n' '$(LAUNCHER)'
	@printf 'Source:     %s\n' '$(SHARE_DIR)'
	@printf '\n'
	@case ":$$PATH:" in \
	  *":$(BIN_DIR):"*) printf 'Run:        claude-tui\n' ;; \
	  *) printf 'Note: %s is not on your PATH.\n' '$(BIN_DIR)' ; \
	     printf '      Add this to your shell rc:\n' ; \
	     printf '          export PATH="%s:$$PATH"\n' '$(BIN_DIR)' ; \
	     printf '      Or run directly: %s\n' '$(LAUNCHER)' ;; \
	esac

uninstall:
	@if [ -f '$(LAUNCHER)' ]; then \
	  rm -f '$(LAUNCHER)' && printf 'removed %s\n' '$(LAUNCHER)' ; \
	else \
	  printf 'not present: %s\n' '$(LAUNCHER)' ; \
	fi
	@if [ -d '$(SHARE_DIR)' ]; then \
	  rm -rf '$(SHARE_DIR)' && printf 'removed %s\n' '$(SHARE_DIR)' ; \
	else \
	  printf 'not present: %s\n' '$(SHARE_DIR)' ; \
	fi

reinstall: uninstall install
